version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongodb:27017/academic_db
    restart: always
    depends_on:
      mongodb:
        condition: service_started

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
